<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260302155342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE T_Chord_CHR (CHR_Id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, CHR_Name VARCHAR(32) NOT NULL, CHR_Diagram VARCHAR(255) NOT NULL, CHR_IsMajor BOOLEAN DEFAULT true NOT NULL, CHR_NTE_Id INT NOT NULL, PRIMARY KEY (CHR_Id))');
        $this->addSql('CREATE INDEX IDX_43FDEB0695C8AB7 ON T_Chord_CHR (CHR_NTE_Id)');
        $this->addSql('CREATE TABLE T_Note_NTE (NTE_Id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, NTE_Name VARCHAR(8) NOT NULL, NTE_Label VARCHAR(64) NOT NULL, PRIMARY KEY (NTE_Id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
$this->addSql('ALTER TABLE T_Chord_CHR ADD CONSTRAINT FK_43FDEB0695C8AB7 FOREIGN KEY (CHR_NTE_Id) REFERENCES T_Note_NTE (NTE_Id) NOT DEFERRABLE');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE T_Chord_CHR DROP CONSTRAINT FK_43FDEB0695C8AB7');
        $this->addSql('DROP TABLE T_Chord_CHR');
        $this->addSql('DROP TABLE T_Note_NTE');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
