<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314111448 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_music_mus (mus_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mus_title VARCHAR(150) DEFAULT NULL, mus_tempo INT DEFAULT NULL, mus_time_signature VARCHAR(8) DEFAULT NULL, mus_key_signature VARCHAR(16) DEFAULT NULL, mus_favorite BOOLEAN NOT NULL, mus_comment VARCHAR(255) DEFAULT NULL, mus_xmlpath VARCHAR(255) DEFAULT NULL, mus_audiopath VARCHAR(255) DEFAULT NULL, PRIMARY KEY (mus_id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('DROP TABLE t_music_mus');
    }
}
