<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315104527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_video_vdo (vdo_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vdo_video_id VARCHAR(20) NOT NULL, vdo_start_sec DOUBLE PRECISION NOT NULL, PRIMARY KEY (vdo_id))');
        $this->addSql('ALTER TABLE t_music_mus ADD mus_vdo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_music_mus ADD CONSTRAINT FK_4033C754C169AA27 FOREIGN KEY (mus_vdo_id) REFERENCES t_video_vdo (vdo_id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4033C754C169AA27 ON t_music_mus (mus_vdo_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('DROP TABLE t_video_vdo');
        $this->addSql('ALTER TABLE t_music_mus DROP CONSTRAINT FK_4033C754C169AA27');
        $this->addSql('DROP INDEX IDX_4033C754C169AA27');
        $this->addSql('ALTER TABLE t_music_mus DROP mus_vdo_id');
    }
}
