<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260928163652 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_scale_note_snt (snt_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, snt_string INT NOT NULL, snt_fret INT NOT NULL, snt_is_root BOOLEAN DEFAULT false NOT NULL, snt_spo_id INT NOT NULL, PRIMARY KEY (snt_id))');
        $this->addSql('CREATE INDEX IDX_7BE7D5FF19F36E38 ON t_scale_note_snt (snt_spo_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_scale_position_string_fret ON t_scale_note_snt (snt_spo_id, snt_string, snt_fret)');
        $this->addSql('CREATE TABLE t_scale_position_spo (spo_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spo_position_number INT NOT NULL, spo_start_fret INT NOT NULL, spo_scl_id INT NOT NULL, PRIMARY KEY (spo_id))');
        $this->addSql('CREATE INDEX IDX_F27F18E269D5981A ON t_scale_position_spo (spo_scl_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_scale_position_number ON t_scale_position_spo (spo_scl_id, spo_position_number)');
        $this->addSql('CREATE TABLE t_scale_scl (scl_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scl_name VARCHAR(64) NOT NULL, scl_type VARCHAR(32) NOT NULL, scl_nte_id INT NOT NULL, PRIMARY KEY (scl_id))');
        $this->addSql('CREATE INDEX IDX_3601B9B76297F410 ON t_scale_scl (scl_nte_id)');
        $this->addSql('ALTER TABLE t_scale_note_snt ADD CONSTRAINT FK_7BE7D5FF19F36E38 FOREIGN KEY (snt_spo_id) REFERENCES t_scale_position_spo (spo_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE t_scale_position_spo ADD CONSTRAINT FK_F27F18E269D5981A FOREIGN KEY (spo_scl_id) REFERENCES t_scale_scl (scl_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE t_scale_scl ADD CONSTRAINT FK_3601B9B76297F410 FOREIGN KEY (scl_nte_id) REFERENCES t_note_nte (nte_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('ALTER TABLE t_scale_note_snt DROP CONSTRAINT FK_7BE7D5FF19F36E38');
        $this->addSql('ALTER TABLE t_scale_position_spo DROP CONSTRAINT FK_F27F18E269D5981A');
        $this->addSql('ALTER TABLE t_scale_scl DROP CONSTRAINT FK_3601B9B76297F410');
        $this->addSql('DROP TABLE t_scale_note_snt');
        $this->addSql('DROP TABLE t_scale_position_spo');
        $this->addSql('DROP TABLE t_scale_scl');
    }
}
