<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927165904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_chord_position_cpo (cpo_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cpo_string INT NOT NULL, cpo_fret INT NOT NULL, cpo_chr_id INT NOT NULL, PRIMARY KEY (cpo_id))');
        $this->addSql('CREATE INDEX IDX_61EC63778ABB0AD4 ON t_chord_position_cpo (cpo_chr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_chord_string ON t_chord_position_cpo (cpo_chr_id, cpo_string)');
        $this->addSql('ALTER TABLE t_chord_position_cpo ADD CONSTRAINT FK_61EC63778ABB0AD4 FOREIGN KEY (cpo_chr_id) REFERENCES t_chord_chr (chr_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE t_chord_chr ADD chr_barre_fret INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_chord_chr ADD chr_barre_from_string INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_chord_chr ADD chr_barre_to_string INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_chord_chr ADD chr_muted_strings TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_chord_chr DROP chr_diagram');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('ALTER TABLE t_chord_position_cpo DROP CONSTRAINT FK_61EC63778ABB0AD4');
        $this->addSql('DROP TABLE t_chord_position_cpo');
        $this->addSql('ALTER TABLE t_chord_chr ADD chr_diagram TEXT NOT NULL');
        $this->addSql('ALTER TABLE t_chord_chr DROP chr_barre_fret');
        $this->addSql('ALTER TABLE t_chord_chr DROP chr_barre_from_string');
        $this->addSql('ALTER TABLE t_chord_chr DROP chr_barre_to_string');
        $this->addSql('ALTER TABLE t_chord_chr DROP chr_muted_strings');
    }
}
