<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314142921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_beat_bea (bea_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bea_pitch_step VARCHAR(2) DEFAULT NULL, bea_pitch_octave INT DEFAULT NULL, bea_pitch_alter DOUBLE PRECISION DEFAULT NULL, bea_duration INT NOT NULL, bea_type VARCHAR(16) NOT NULL, bea_dot BOOLEAN NOT NULL, bea_string INT DEFAULT NULL, bea_fret INT DEFAULT NULL, bea_measure_id INT DEFAULT NULL, PRIMARY KEY (bea_id))');
        $this->addSql('CREATE INDEX IDX_CF7B53D1494C47FD ON t_beat_bea (bea_measure_id)');
        $this->addSql('CREATE TABLE t_measure_mea (mea_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mea_numero INT NOT NULL, mea_tempo INT DEFAULT NULL, mea_time_signature VARCHAR(32) DEFAULT NULL, mea_mus_id INT DEFAULT NULL, PRIMARY KEY (mea_id))');
        $this->addSql('CREATE INDEX IDX_A6A9A0A27D697A4D ON t_measure_mea (mea_mus_id)');
        $this->addSql('ALTER TABLE t_beat_bea ADD CONSTRAINT FK_CF7B53D1494C47FD FOREIGN KEY (bea_measure_id) REFERENCES t_measure_mea (mea_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE t_measure_mea ADD CONSTRAINT FK_A6A9A0A27D697A4D FOREIGN KEY (mea_mus_id) REFERENCES t_music_mus (mus_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('ALTER TABLE t_beat_bea DROP CONSTRAINT FK_CF7B53D1494C47FD');
        $this->addSql('ALTER TABLE t_measure_mea DROP CONSTRAINT FK_A6A9A0A27D697A4D');
        $this->addSql('DROP TABLE t_beat_bea');
        $this->addSql('DROP TABLE t_measure_mea');
    }
}
